# This is a basic workflow to help you get started with Actions

name: M3U generator

# Controls when the action will run. 
on:
  schedule:
    - cron: '0 0/3 * * *'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4
      - name: yt
        run: |
          rm -rf yt-dlp.*
          wget https://github.com/yt-dlp/yt-dlp/releases/latest/download/yt-dlp
          chmod +x ./yt-dlp
          ls
      # Runs a single command using the runners shell
      #- name: Run a one-line script
      #  run: echo testing!
      - name: pip
        run: pip install requests
      # Runs a set of commands using the runners shell 
      - name: config
        run: |
          git config --global user.email "action@github.com"
          git config --global user.name "GitHub Action"
      - name: a
        run: echo '#EXTM3U' > youtube.m3u8
      - name: b
        run: echo '#EXT-X-VERSION:3' >> youtube.m3u8
      - name: c
        run: echo '#EXT-X-STREAM-INF:RESOLUTION=1280x720' >> youtube.m3u8
      - name: Main
        run: ./yt-dlp -g 'https://www.youtube.com/@euronewshu/live' --cookies cookies.firefox-private.txt >> youtube.m3u8
      - name: d
        run: echo '#EXT-X-ENDLIST' >> youtube.m3u8
      - name: git add
        run: |
          git add -A
          ls -la

      - name: commit & push
        run: |
          git commit -m "links are updated"
          git push -f
